# Generated by Django 6.0 on 2026-02-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_progresslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('active', 'Active')], default='light', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_run',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_swim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_asthma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progresslog',
            name='craving_level',
            field=models.IntegerField(default=0, help_text='0–10 scale'),
        ),
        migrations.AddField(
            model_name='progresslog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cigarettes_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='craving_level',
            field=models.IntegerField(blank=True, help_text='0–10 scale', null=True),
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='cigarettes_smoked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='money_saved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
