# Generated by Django 6.0.4 on 2026-04-10 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_activity_level_profile_can_run_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activity_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='craving_level',
        ),
        migrations.AddField(
            model_name='profile',
            name='breathlessness',
            field=models.CharField(blank=True, choices=[('always', 'Yes always'), ('sometimes', 'Sometimes'), ('rarely', 'Rarely'), ('never', 'Never')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_cycle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_walk',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='craving_trigger',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('meals', 'After meals'), ('stress', 'During stress'), ('social', 'Social situations')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fitness_level',
            field=models.CharField(blank=True, choices=[('very_low', 'Very Low'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='general_health',
            field=models.CharField(blank=True, choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_heart_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_injuries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_joint_problems',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='lifestyle',
            field=models.CharField(blank=True, choices=[('sitting', 'Mostly sitting (desk job/student)'), ('mixed', 'Mix of sitting and moving'), ('feet', 'Mostly on my feet'), ('active', 'Physically active job')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='motivation_level',
            field=models.CharField(blank=True, choices=[('low', 'Not very motivated'), ('medium', 'Somewhat motivated'), ('high', 'Motivated'), ('very_high', 'Very motivated')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='questionnaire_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='quit_attempts',
            field=models.CharField(blank=True, choices=[('never', 'Never tried'), ('once', 'Tried once'), ('multiple', 'Tried multiple times'), ('reducing', 'Currently reducing')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='quit_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoking_duration',
            field=models.CharField(blank=True, choices=[('less_1', 'Less than 1 year'), ('1_to_5', '1-5 years'), ('5_to_10', '5-10 years'), ('10_plus', '10+ years')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='starting_feeling',
            field=models.CharField(blank=True, choices=[('nervous', 'Nervous / Unsure'), ('worried', 'Ready but worried'), ('confident', 'Confident'), ('excited', 'Very excited')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='time_available',
            field=models.CharField(blank=True, choices=[('less_10', 'Less than 10 minutes'), ('10_to_20', '10-20 minutes'), ('20_to_30', '20-30 minutes'), ('30_plus', '30+ minutes')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='can_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='craving_level',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(choices=[('first_step', '🌱 First Step'), ('logger', '📋 Logger'), ('on_fire', '🔥 On Fire'), ('two_weeks', '💪 Two Weeks'), ('one_month', '🏆 One Month'), ('money_saver', '💰 Money Saver'), ('calm_mind', '🧘 Calm Mind'), ('dedicated', '⭐ Dedicated')], max_length=30)),
                ('earned_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
